defaults :
  - modulus_default        
  - arch:
    - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

arch:
  fully_connected:
    layer_size: 30
    nr_layers: 2

scheduler:
  decay_rate: 0.95
  decay_steps: 100

training:
  rec_results_freq: 1000
  max_steps : 8000

batch_size:
  IC: 100
  BC: 50
  interior: 2000